apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: query
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment-retrieval-api.yaml
  - deployment-reranker.yaml
  - deployment-mcp-server.yaml
  - service.yaml
  - httproute.yaml
  - securitypolicy.yaml
  - hpa.yaml
